name: Test
on:
  push:
    branches: [ main ]

env:
  AWS_DEFAULT_REGION: us-west-2
  run-name: ${{ github.actor }} is testing out GitHub Actions 🚀


jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Print
      run: |
        echo "SHA: $GITHUB_SHA"
      
